//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingItem()
        {
            this.ServiceBookings = new HashSet<ServiceBooking>();
        }
    
        public int BT_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> SubTotal { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
    }
}
