//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        public int Design_ID { get; set; }
        public string Design_Code { get; set; }
        public string Design_Image { get; set; }
        public Nullable<int> Design_Price { get; set; }
    }
}
