//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_City { get; set; }
        public string Customer_Address { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
