//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measurment()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Measurment_ID { get; set; }
        public Nullable<int> Measurment_Type_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Chest { get; set; }
        public Nullable<double> Shoulder { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Sleeves { get; set; }
        public Nullable<double> arms { get; set; }
        public Nullable<double> Collar { get; set; }
        public Nullable<double> Bottom { get; set; }
        public string SidePocket { get; set; }
        public string FrontPocket { get; set; }
    
        public virtual MeasurmentType MeasurmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
