//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBooking
    {
        public int SB_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public Nullable<int> BT_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual BookingItem BookingItem { get; set; }
    }
}
