//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRTailor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_Address { get; set; }
        public string Staff_Phone { get; set; }
        public string Staff_Position { get; set; }
        public string Staff_CNIC { get; set; }
        public string Staff_image { get; set; }
        public string Staff_Email { get; set; }
        public Nullable<int> OrdersCompleted { get; set; }
        public Nullable<int> OrdersInProcess { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
